USE carreras;
CREATE TABLE c_uni (nombre VARCHAR(255) NOT NULL, demanda DECIMAL(4,1) NOT NULL , tasa_paro DECIMAL(4,1) NOT NULL);
INSERT INTO c_uni VALUES ('Ldo. en Medicina', 94.3, 5.7);
INSERT INTO c_uni VALUES ('Ingeniero en Electrónica', 93.0, 7.0);
INSERT INTO c_uni VALUES ('Ldo. en Ciencias y Técnicas Estadísticas', 92.8, 7.2);
INSERT INTO c_uni VALUES ('Ingeniero en Informática', 91.7, 8.3);
INSERT INTO c_uni VALUES ('Diplomado en Óptica y Optometría', 91.2, 8.8);
INSERT INTO c_uni VALUES ('Ldo. en Ciencias y Tecnología de los Alimentos', 90.3, 9.7);
INSERT INTO c_uni VALUES ('Ingeniero Técnico en Informática de Sistemas', 89.9, 10.1);
INSERT INTO c_uni VALUES ('Ldo. en Odontología', 89.5, 10.5);
INSERT INTO c_uni VALUES ('Diplomado en Logopedia', 89.3, 10.7);
INSERT INTO c_uni VALUES ('Ldo. en Farmacia', 88.3, 11.7);
INSERT INTO c_uni VALUES ('Mestro-Especialidad de Lengua Extranjera', 87.0, 13.0);
INSERT INTO c_uni VALUES ('Ingeniero Técnico en Informática de Gestión', 86.7, 13.3);
INSERT INTO c_uni VALUES ('Diplomado en Terapia Ocupacional', 86.2, 13.8);
INSERT INTO c_uni VALUES ('Ldo. en Investigación y Técnicas de Mercado', 86.0, 14.0);
INSERT INTO c_uni VALUES ('Ldo. en Ciencias del Trabajo', 85.5, 14.5);
INSERT INTO c_uni VALUES ('Ldo. en Administración y Dirección de Empresas', 85.2, 14.8);
INSERT INTO c_uni VALUES ('Ldo. en Ciencias de la Actividad Física y del Deporte', 85.0, 15.0);